# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_auto_20160702_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='aluno.Professor'),
        ),
    ]
